#
#    Copyright 2024-present Jan Haenel
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
spring:
  application:
    name: HiveMQ-CE embedded Demo

# Logging: Important to import the logback-spring.xml, HiveMQs will take precedence otherwise
logging:
  config: classpath:logback-spring.xml
  name: application
  path: log
  file:
    name: log/application.log

# Configuration for hivemq-spring-boot-starter
# Can get commented out at all to have absolute default behaviour
hivemq:
  enabled: true
  auto-start: false
  config.folder: .hivemq/conf
  data.folder: .hivemq/data
  extensions.folder: .hivemq/extensions
  extensions.collector.enabled: true
  extensions.collector.info.publish: true
  extensions.collector.info.topic: "boot/extensions"
  log.folder: ${logging.path}
  log.level: info

  # HiveMQ-CE specific configuration
  config:
    listeners:
      tcp-listeners:
        - name: default-tcp-listener
          port: 1883
          bind-address: 0.0.0.0

    mqtt:
      keep-alive.allow-unlimited: false
      keep-alive.max-keep-alive: 65535
      message-expiry.max-interval: 3600
      queued-messages.max-queue-size: 1000
      queued-messages.strategy: discard-oldest
      receive-maximum.server-receive-maximum: 10
      retained-messages.enabled: true
      session-expiry.max-interval: 60
      shared-subscriptions.enabled: true
      subscription-identifier.enabled: true
      topic-alias.enabled: true
      topic-alias.max-per-client: 5
      wildcard-subscriptions.enabled: true

    persistence:
      mode: in-memory

    security:
      allow-empty-client-id.enabled: false
      payload-format-validation.enabled: false
      utf8-validation.enabled: true
      allow-request-problem-information.enabled: true
